---
# This simple Ansible playbook launches docker

- name: Start Docker
  hosts: localhost
  connection: local
  become: true  # Gives root privileges to be able to run docker

  # vars used in this project
  vars:
    var_docker: "docker"
    var_netdata: "netdata"

  tasks:
    - name: Start Docker cli
      systemd:  # Start the program in question
        name: "{{ var_docker }}" 
        state: started # if Docker is on, then this command does nothing. If not on then this command starts Docker

    - name: Verify that Docker is working
      command: "{{ var_docker }} --version"
      register: docker_output  # Save the output of the previous command
      changed_when: false  # Won't change any files, only checks the version. Won't show as yellow, will show green 

    - name: Display Docker status
      debug:
        msg: |
          Docker is now running!
          {{ docker_output.stdout }}

                                    ##        .            
                      ## ## ##        ==            
                   ## ## ## ##       ===            
               /""""""""""""""""\___/ ===        
          ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
               \______ o           __/            
                 \    \        __/             
                  \____\______/                

                  |          |
               __ |  __   __ | _  __   _
              /  \| /  \ /   |/  / _\ | 
              \__/| \__/ \__ |\_ \__  |

    - name: Netdata 
      community.docker.docker_container:
        name: "{{ var_netdata }}"
        image: netdata/netdata:stable
        state: started
        ports:
          - "19999:19999"
        capabilities:
          - SYS_PTRACE # Allows you to see which programs are taking up CPU, memory, etc. 
        volumes:
          - /proc:/host/proc:ro # Shows system info (cpu, ram, etc)
          - /sys:/host/sys:ro # Shows hardware info (nic, temperature, disk space, etc) 
          - /var/run/docker.sock:/var/run/docker.sock:ro # Lets it see the docker containers and their stats
        
